### ISSUE TITLE
Modernize library, introduce generic interface

### ISSUE THREAD

**Issue by umputun** [go-pkgz/lcw#31]
With go 1.18 we can make use of generics to simplify the API. I mean the primary access methods

```go
Get(key string, fn func() (interface{}, error)) (val interface{}, err error) // load or get from cache
Peek(key string) (interface{}, bool)                                        
```

this change will make usage much easier. In addition, we may want to update dependencies

_note: this is a breaking change and should be released as v2. As of now, we don't even have v1, so we will need to tag the current one as v1.0.0 first_

@paskal - let me know if you want to deal with this

**Comment by paskal** [comment]
Redis will work with generics only if keys would be restricted to something like `fmt.Stringer` or kept as strings:
![telegram-cloud-photo-size-2-5231252703647220141-y](https://user-images.githubusercontent.com/712534/188287884-35660d27-024d-43c6-8302-ff85fd929d05.jpg)
![telegram-cloud-photo-size-2-5231252703647220142-y](https://user-images.githubusercontent.com/712534/188287890-e7bd4f1c-1b5f-4087-a246-1ae629573add.jpg)
And then there are still problems. Value in Redis is a key which works only with `interface{}` but not `V any`.
![telegram-cloud-photo-size-2-5231252703647220167-y](https://user-images.githubusercontent.com/712534/188287896-7a36284a-d5ad-4564-8a5e-0f04183053ee.jpg)
And keys are failing apart as well, as they are returned as a list of strings and it's impossible to put them into Invalidate function:
![telegram-cloud-photo-size-2-5231252703647220197-y](https://user-images.githubusercontent.com/712534/188287905-fe1f59c4-c828-4c3d-a986-55d0ebe21eb9.jpg)

WDYT?

**Comment by umputun** [comment]
The first point makes sense but practically limits other caches significantly. Actually, it doesn't even need generics if all we want is stringrer as a key.

Regarding the second point, I don't really understand what the issue is because, as far as I recall, `any` is an alias for `interface{}` and is supposed to be interchangeable. Are you sure those errors you showed are real and not some bug on IDEA side?

**Comment by paskal** [comment]
It's Go itself:

```
~/lcw/v2 paskal/generics +5 !9 ❯ go test ./... -count 1
# github.com/go-pkgz/lcw/v2 [github.com/go-pkgz/lcw/v2.test]
./redis_cache.go:51:10: cannot use v (variable of type string) as type V in return statement
./redis_cache.go:61:10: cannot use v (variable of type string) as type V in return statement
```

`interface{}` means "anything", `any` means "put there anything but then stick to using that type". I don't think it's solvable for the Redis cache.

**Comment by paskal** [comment]
Also:
```
~/lcw/v2 paskal/generics +5 !9 ❯ go test ./... -count 1
# github.com/go-pkgz/lcw/v2 [github.com/go-pkgz/lcw/v2.test]
./redis_cache.go:143:14: invalid operation: cannot use type assertion on type parameter value data (variable of type V constrained by any)
```

<img width="814" alt="image" src="https://user-images.githubusercontent.com/712534/188764711-73cebe51-e38e-4694-bdab-637c90a4d213.png">

The only way forward with generics is without Redis and with dropping the size check support. I think we shouldn't go in that direction.

**Comment by umputun** [comment]
> interface{} means "anything", any means "put there anything but then stick to using that type". I don't think it's solvable for the Redis cache.

Well, this is surprising and even confusing as `any` is literally defined as an alias type for interface{}. This is from the source of go SDK, package `builtin`: 

```
// any is an alias for interface{} and is equivalent to interface{} in all ways.
type any = interface{}` 
```

**Comment by paskal** [comment]
I can't make it work, unfortunately. The current state of generics doesn't allow this use case to work unless we'll have Redis library supporting generics.

**Comment by umputun** [comment]
ok, let's kill it for now

**Comment by paskal** [comment]
If anyone would be willing to try it, my latest attempt is stored in the [paskal/generics](https://github.com/go-pkgz/lcw/tree/paskal/generics) branch.
